name: hackzurich2020
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bot_toast: 2.2.1
  fast_qr_reader_view:
    git:
      url: git://github.com/SoftWyer/fast_qr_reader_view.git
  firebase_auth: ^0.15.4
  google_fonts: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
